name = "ai-worker"
compatibility_date = "2025-06-25"

# 所有环境通用变量
[vars]
TIMEZONE = "Asia/Shanghai"

# 开发环境配置
[env.dev]
main = "r2-worker.js"
workers_dev = true

[env.dev.vars]
TIMEZONE = "Asia/Shanghai"
SILICON_FLOW_API_KEY = "sk-dev-xxxxx"
DEBUG_MODE = "true"
LOG_LEVEL = "debug"

[env.dev.observability]
logs.enabled = true

[[env.dev.r2_buckets]]
binding = "AI_IMAGES"
bucket_name = "ai-generated-images-dev"

# 生产环境配置
[env.production]
main = "r2-worker.js"
workers_dev = false
routes = [
  { pattern = "ai.worker.nxlan.cn", custom_domain = true }
]

[env.production.vars]
TIMEZONE = "Asia/Shanghai"
LOG_LEVEL = "error"

[env.production.observability]
logs.enabled = true

[[env.production.r2_buckets]]
binding = "AI_IMAGES"
bucket_name = "ai-generated-images"

# 部署生产环境：wrangler deploy --env production
# 部署开发环境：wrangler deploy --env dev

# 使用Cloudflare Secret管理生成环境API密钥
# 运行: wrangler secret put SILICON_FLOW_API_KEY --env production