name = "ai-worker"
main = "r2-worker.js"
compatibility_date = "2025-06-25"

# 所有环境通用变量
[vars]
TIMEZONE = "Asia/Shanghai"

# 开发环境配置
[env.dev]
workers_dev = true
route = "dev-ai.worker.nxlan.cn/*"
vars.SILICON_FLOW_API_KEY = "sk-lsvigtdephufbkhxlhuhcpschibwzzegcbqxzzwvydaqwvmy"   # 硅基流动测试API
vars.TIMEZONE = "Asia/Shanghai"  

[[env.dev.r2_buckets]]
binding = "AI_IMAGES"
bucket_name = "ai-generated-images-dev"

# 生产环境配置
[env.production]
workers_dev = false
route = "ai.worker.nxlan.cn/*"
custom_domain = "ai.worker.nxlan.cn"
vars.TIMEZONE = "Asia/Shanghai" 

[[env.production.r2_buckets]]
binding = "AI_IMAGES"
bucket_name = "ai-generated-images"


# 部署生产环境：wrangler deploy --env production
# 部署开发环境：wrangler deploy --env dev

# 使用Cloudflare Secret管理生成环境API密钥
# 运行: wrangler secret put SILICON_FLOW_API_KEY --env production